# Version of docker-compose syntax
version: "3.9"

# Main block could be one or more service blocks
services:
  # Name of our service
  app:
    # Build the docker container inside our current directory
    build:
      context: .
      # For running docker-compose in dev mode
      args:
        - DEV=true
    # Maps one of our ports to a containers port
    ports:
      - "8000:8000"
    # Mapping dirs from our system into the docker container
    volumes:
      - "./app:/app"
    # Commands that is used to run the service
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # Add environment variables
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # Start app after db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data:
